import type { ComponentDefinition } from "../../../../parseNodeDefs.ts";

export default {
  name: "Label",
  extends: "ControlProps",
  props: {
    autowrap_mode: "0 | 1 | 2 | 3",
    clip_text: "boolean",
    ellipsis_char: "string",
    horizontal_alignment: "0 | 1 | 2 | 3",
    justification_flags: "BitFieldType",
    label_settings: "LabelSettings",
    language: "string",
    lines_skipped: "number",
    max_lines_visible: "number",
    mouse_filter: "0 | 1 | 2",
    size_flags_vertical: "BitFieldType",
    structured_text_bidi_override: "0 | 1 | 2 | 3 | 4 | 5 | 6",
    structured_text_bidi_override_options: "string[]",
    tab_stops: "number[]",
    text: "string",
    text_direction: "0 | 1 | 2 | 3",
    text_overrun_behavior: "0 | 1 | 2 | 3 | 4",
    uppercase: "boolean",
    vertical_alignment: "0 | 1 | 2 | 3",
    visible_characters: "number",
    visible_characters_behavior: "0 | 1 | 2 | 3 | 4",
    visible_ratio: "number",
  },
  category: "Control",
  docs: [
    "A control for displaying plain text.",
    "",
    "@example",
    "```tsx",
    '<Label text="Hello World" />',
    "```",
  ],
  docsHref: "https://docs.godotengine.org/en/stable/classes/class_label.html",
} as ComponentDefinition;
