import {
  Byte,
  type ByteType,
  createGodactScene,
  createTileSet,
  Node2D,
  PackedArray,
  TileMapLayer,
} from "@inbestigator/godact";

function MainScene() {
  return (
    <Node2D name="MainScene">
      <TileMapLayer
        tile_set={createTileSet({
          path: "res://tile_set.tres",
        })}
        tile_map_data={PackedArray<ByteType>(
          Byte(
            "AAD//wAAAQADAAQAAAAAAAAAAQAEAAQAAAAAAP//AQAEAAMAAAD/////AQADAAMAAAABAP//AQAFAAMAAAACAP//AQAGAAMAAAADAP//AQAHAAMAAAADAAAAAQAHAAQAAAADAAEAAQAHAAUAAAADAAIAAQAHAAYAAAADAAMAAQAHAAcAAAACAAMAAQAGAAcAAAABAAMAAQAFAAcAAAAAAAMAAQAEAAcAAAAAAAIAAQAEAAYAAAAAAAEAAQAEAAUAAAABAAEAAQAFAAUAAAABAAIAAQAFAAYAAAACAAIAAQAGAAYAAAACAAEAAQAGAAUAAAACAAAAAQAGAAQAAAABAAAAAQAFAAQAAAD//wEAAQADAAUAAAD//wIAAQADAAYAAAD//wMAAQADAAcAAAD+/wMAAQACAAcAAAD9/wMAAQABAAcAAAD8/wMAAQAAAAcAAAD8/wEAAQAAAAUAAAD8/wIAAQAAAAYAAAD8/wAAAQAAAAQAAAD9/wAAAQABAAQAAAD+/wAAAQACAAQAAAD+/wEAAQACAAUAAAD+/wIAAQACAAYAAAD9/wIAAQABAAYAAAD9/wEAAQABAAUAAAD9////AQABAAMAAAD+////AQACAAMAAAD8////AQAAAAMAAAD8//7/AQAAAAIAAAD8//3/AQAAAAEAAAD8//z/AQAAAAAAAAD+//z/AQACAAAAAAD9//z/AQABAAAAAAD///z/AQADAAAAAAAAAPz/AQAEAAAAAAABAPz/AQAFAAAAAAACAPz/AQAGAAAAAAADAPz/AQAHAAAAAAADAP3/AQAHAAEAAAADAP7/AQAHAAIAAAD9//3/AQABAAEAAAD9//7/AQABAAIAAAD+//3/AQACAAEAAAD+//7/AQACAAIAAAD///3/AQADAAEAAAD///7/AQADAAIAAAAAAP3/AQAEAAEAAAAAAP7/AQAEAAIAAAABAP3/AQAFAAEAAAABAP7/AQAFAAIAAAACAP3/AQAGAAEAAAACAP7/AQAGAAIAAAA=",
          ),
        )}
      />
    </Node2D>
  );
}

createGodactScene(<MainScene />, "./examples/main.tscn");
