/**
 * Return type for Byte
 *
 * @category Utility
 */
export interface ByteType {
  type: "Wrapped";
  wrapper: "Byte";
  value: string;
}

/**
 * Pack many variables of the same type into a single array
 *
 * @example
 * ```tsx
 * Byte("AAD//wAAAQADAAQAAAAAAAAAAQAEAAQAAAAAAP//AQAEAAMAAAD/////AQADAAMAAAABAP//AQAFAAMAAAACAP//AQAGAAMAAAADAP//AQAHAAMAAAADAAAAAQAHAAQAAAADAAEAAQAHAAUAAAADAAIAAQAHAAYAAAADAAMAAQAHAAcAAAACAAMAAQAGAAcAAAABAAMAAQAFAAcAAAAAAAMAAQAEAAcAAAAAAAIAAQAEAAYAAAAAAAEAAQAEAAUAAAABAAEAAQAFAAUAAAABAAIAAQAFAAYAAAACAAIAAQAGAAYAAAACAAEAAQAGAAUAAAACAAAAAQAGAAQAAAABAAAAAQAFAAQAAAD//wEAAQADAAUAAAD//wIAAQADAAYAAAD//wMAAQADAAcAAAD+/wMAAQACAAcAAAD9/wMAAQABAAcAAAD8/wMAAQAAAAcAAAD8/wEAAQAAAAUAAAD8/wIAAQAAAAYAAAD8/wAAAQAAAAQAAAD9/wAAAQABAAQAAAD+/wAAAQACAAQAAAD+/wEAAQACAAUAAAD+/wIAAQACAAYAAAD9/wIAAQABAAYAAAD9/wEAAQABAAUAAAD9////AQABAAMAAAD+////AQACAAMAAAD8////AQAAAAMAAAD8//7/AQAAAAIAAAD8//3/AQAAAAEAAAD8//z/AQAAAAAAAAD+//z/AQACAAAAAAD9//z/AQABAAAAAAD///z/AQADAAAAAAAAAPz/AQAEAAAAAAABAPz/AQAFAAAAAAACAPz/AQAGAAAAAAADAPz/AQAHAAAAAAADAP3/AQAHAAEAAAADAP7/AQAHAAIAAAD9//3/AQABAAEAAAD9//7/AQABAAIAAAD+//3/AQACAAEAAAD+//7/AQACAAIAAAD///3/AQADAAEAAAD///7/AQADAAIAAAAAAP3/AQAEAAEAAAAAAP7/AQAEAAIAAAABAP3/AQAFAAEAAAABAP7/AQAFAAIAAAACAP3/AQAGAAEAAAACAP7/AQAGAAIAAAA=");
 * ```
 *
 * @category Utility
 * @see https://docs.godotengine.org/en/stable/classes/class_packedbytearray.html
 */
export function Byte(value: string): ByteType {
  return {
    type: "Wrapped",
    wrapper: "Byte",
    value: value,
  };
}
